version: "3"

services:

  backend:
    image: openjdk:jre # yep, we need bash, no apline sorry
    command: /be.jar
    ports:
      - "8080:8080" # QA fellows like to get to the backend straight
    volumes:
      - ./be.jar:/be.jar
      - ./be.conf:/be.conf
      - ./be-logs:/logs

  proxy:
    image: nginx:alpine
    ports:
    - "80:80"
    links:
      - backend
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./dist-fe:/frontend

#  postgres:
#    image: postgres
#    volumes:
#      - db-data:/var/lib/db
#
#volumes:
#  db-data:
