version: "3"

services:

  backend:
    build: ./backend/backend
    ports:
      - "8080:8080" # QA fellows like to get to the backend straight
    volumes:
      - ./be.jar:/be.jar:ro
      - ./be.conf:/be.conf:ro
      - ./be-logs:/logs

  frontend:
    build: ./frontend
    volumes:
      - frontend-assets:/build/build

  proxy:
    image: nginx:alpine
    ports:
    - "80:80"
    links:
      - backend
      - frontend
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - frontend-assets:/frontend:ro

#  postgres:
#    image: postgres
#    volumes:
#      - db-data:/var/lib/db
#
#  db-data:

volumes:
  frontend-assets:
